const SUPABASE_URL='https://rnwtvkhnhybdgxhmgebw.supabase.co';
const SUPABASE_KEY='sb_publishable_r00Qvz_GBmRi4fVj6O7scA_jIj9wuyN';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const S={user:null,p:[],e:[],t:[],o:[],v:[],q:[],qLoaded:{},i:[],docs:[],sources:[],tab:'resumen',open:{},context:null,historyPage:0};
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const num=n=>{n=Number(n)||0;const a=Math.abs(n),d=a&&a<.001?8:a<.01?6:a<.1?5:3;return new Intl.NumberFormat('es-ES',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n)};
const date=d=>d?new Intl.DateTimeFormat('es-ES').format(new Date(String(d).slice(0,10)+'T00:00:00')):'—';
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const tn=p=>S.t.find(x=>x.id===p.tipo_productoo_id)?.nombre||S.t.find(x=>x.id===p.tipo_producto_id)?.nombre||'Sin categoría';
const en=p=>S.e.find(x=>x.id===p.entidad_financiera_id)?.nombre||'Sin entidad';
const account=p=>['Cuenta corriente','Cuenta de ahorro','Cuenta de inversión'].includes(tn(p));
const active=()=>S.p.filter(p=>p.activo!==false);
const delta=o=>{const t=o.tipo_operacion||'',n=Number(o.cantidad)||0;if(['Compra','Aportacion','Aportación','Acciones liberadas','Dividendo en acciones','Split'].includes(t))return Math.abs(n);if(t==='Venta')return -Math.abs(n);if(['Ajuste de posición','Traspaso'].includes(t))return n;return 0};
function costBasis(id){
 const ops=S.o.filter(x=>x.producto_id===id).slice().sort((a,b)=>String(a.fecha).localeCompare(String(b.fecha))||String(a.id).localeCompare(String(b.id))),lots=[];
 const add=(q,c)=>{if(q>0)lots.push({qty:q,cost:c})};
 for(const o of ops){const t=o.tipo_operacion||'',q=Math.abs(Number(o.cantidad)||0),pu=Number(o.precio_unitario)||0;if(!q)continue;
  if(t==='Compra'||t==='Aportacion'||t==='Aportación'){add(q,Number(o.importe_neto)>0?Number(o.importe_neto):q*pu)}
  else if(t==='Venta'){let left=q;while(left>1e-12&&lots.length){const l=lots[0],take=Math.min(left,l.qty),u=l.qty?l.cost/l.qty:0;l.qty-=take;l.cost-=take*u;left-=take;if(l.qty<=1e-12)lots.shift()}}
  else if(t==='Acciones liberadas'||t==='Dividendo en acciones'){if(lots.length){const totalQty=lots.reduce((a,l)=>a+l.qty,0);for(const l of lots)l.qty+=q*(l.qty/totalQty)}else add(q,0)}
  else if(t==='Split'){if(lots.length){const totalQty=lots.reduce((a,l)=>a+l.qty,0);if(totalQty>0){for(const l of lots)l.qty+=q*(l.qty/totalQty)}}else add(q,0)}
  else if(t==='Ajuste de posición'||t==='Traspaso'){if(Number(o.cantidad)>0)add(q,q*pu);else{let left=q;while(left>1e-12&&lots.length){const l=lots[0],take=Math.min(left,l.qty),u=l.qty?l.cost/l.qty:0;l.qty-=take;l.cost-=take*u;left-=take;if(l.qty<=1e-12)lots.shift()}}}
 }
 const totalQty=lots.reduce((a,l)=>a+l.qty,0),totalCost=lots.reduce((a,l)=>a+l.cost,0);
 return {lots,totalQty,totalCost,avg:totalQty?totalCost/totalQty:0};
}
const qty=id=>{const c=costBasis(id);return c.totalQty||S.o.filter(x=>x.producto_id===id).reduce((a,x)=>a+delta(x),0)};
const histV=id=>S.v.filter(x=>x.producto_id===id&&String(x.fecha).slice(0,10)<=today()).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));
const histQ=id=>S.q.filter(x=>x.producto_id===id&&String(x.fecha).slice(0,10)<=today()).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));
const lastV=id=>histV(id)[0]; const lastQ=id=>histQ(id)[0];
const currentUnit=p=>lastQ(p.id)?.cierre??lastV(p.id)?.precio_unitario??null;
const currentDate=p=>lastQ(p.id)?.fecha??lastV(p.id)?.fecha??null;
function val(p){const q=lastQ(p.id),v=lastV(p.id);if(account(p))return Number(v?.valor_total)||0;if(q&&qty(p.id))return Number(q.cierre||0)*qty(p.id)*Number(q.factor_conversion||1);if(v&&v.valor_total!=null)return Number(v.valor_total)||0;return 0}
function oldVal(p){const h=histV(p.id);return h[1]?Number(h[1].valor_total)||0:0}
function cost(p){if(account(p))return null;const c=costBasis(p.id);return c.totalQty?c.totalCost:null}
function diff(p){const c=cost(p);return c==null?val(p)-oldVal(p):val(p)-c}
function pct(p){const c=cost(p);return c?diff(p)/c*100:0}
function groups(){const g={};active().forEach(p=>(g[p.entidad_financiera_id]??=[]).push(p));return g}
async function latestQuotes(ids){const out=[];await Promise.all(ids.map(async id=>{const r=await db.from('cotizaciones_historicas').select('producto_id,fecha,cierre,factor_conversion').eq('producto_id',id).order('fecha',{ascending:false}).limit(1);if(!r.error&&r.data?.[0])out.push(r.data[0])}));S.q.push(...out);return out}
async function ensureQuotes(id){if(S.qLoaded[id])return histQ(id);const r=await db.from('cotizaciones_historicas').select('producto_id,fecha,cierre,factor_conversion').eq('producto_id',id).order('fecha',{ascending:false});if(r.error)throw r.error;S.q=S.q.filter(x=>x.producto_id!==id).concat(r.data||[]);S.qLoaded[id]=true;return r.data||[]}
async function load(){try{let u=null;try{const gr=await db.auth.getUser();if(gr.error)throw gr.error;u=gr.data?.user||null}catch(authErr){await db.auth.signOut({scope:'local'});login();return}if(!u){login();return}S.user=u;const [p,e,t,o,v,i,d,s]=await Promise.all([db.from('productos').select('*').eq('user_id',u.id),db.from('entidades_financieras').select('*').eq('user_id',u.id),db.from('tipos_productos').select('*').eq('activo',true).order('orden_presentacion'),db.from('operaciones').select('*').eq('user_id',u.id).order('fecha'),db.from('valoraciones_historicas').select('*').eq('user_id',u.id).order('fecha'),db.from('intereses_cuentas').select('*').eq('user_id',u.id).order('fecha',{ascending:false}),db.from('documentos_capturas').select('*').eq('user_id',u.id).order('fecha_documento',{ascending:false}),db.from('fuentes_valoracion').select('*').order('puntuacion',{ascending:false})]);for(const r of [p,e,t,o,v,i,d,s])if(r.error)throw r.error;S.p=p.data||[];S.e=e.data||[];S.t=t.data||[];S.o=o.data||[];S.v=v.data||[];S.i=i.data||[];S.docs=d.data||[];S.sources=s.data||[];S.q=[];await latestQuotes(active().filter(p=>!account(p)).map(p=>p.id));render()}catch(e){$('app').innerHTML='<div class="wrap"><div class="card error"><h2>Error al cargar Patrimonio</h2><p>'+esc(e.message||e)+'</p><button class="btn" onclick="load()">Reintentar</button></div></div>'}}
function login(){$('app').innerHTML='<div class="wrap"><div class="card" style="max-width:430px;margin:100px auto"><h1>Patrimonio</h1><label>Email<input id="em"></label><br><label>Contraseña<input id="pw" type="password"></label><br><button class="btn" onclick="goLogin()">Entrar</button><p id="err"></p></div></div>'}
async function goLogin(){const r=await db.auth.signInWithPassword({email:$('em').value,password:$('pw').value});if(r.error)$('err').innerHTML='<div class="error">'+esc(r.error.message)+'</div>';else load()}
async function logout(){await db.auth.signOut();login()}
function productRows(ps){return '<div class="tablewrap"><table class="ptable"><thead><tr><th>Producto</th><th>Fecha</th><th>Nº títulos</th><th>Coste</th><th>Última cotización</th><th>Valor actual</th><th>Diferencia</th><th>%</th></tr></thead><tbody>'+ps.map(p=>{const unit=currentUnit(p),v=val(p),c=cost(p),d=diff(p),pc=pct(p),dt=currentDate(p);return `<tr onclick="product('${p.id}')"><td><div class="pname">${esc(p.nombre)}</div><span class="pill">${esc(tn(p))}</span></td><td>${date(dt)}</td><td>${account(p)?'—':num(qty(p.id))}</td><td>${c==null?'—':money(c)}</td><td>${account(p)?'—':unit==null?'—':num(unit)+' €'}</td><td><b>${v?money(v):'—'}</b></td><td class="${d>0?'gain':d<0?'loss':''}">${d?(d>0?'+':'')+money(d):'—'}</td><td class="${pc>0?'gain':pc<0?'loss':''}">${pc?(pc>0?'+':'')+pc.toFixed(2)+' %':'—'}</td></tr>`}).join('')+'</tbody></table></div>'}
function entities(){const g=groups();return '<div class="card"><div class="toolbar"><h2>Entidades</h2><button class="btn" onclick="manualData()">＋ Introducir datos</button></div>'+Object.entries(g).map(([id,ps])=>{const e=S.e.find(x=>x.id===id),open=!!S.open[id];return `<div class="entity"><div class="entity-head" onclick="S.open['${id}']=!S.open['${id}'];render()"><div><div class="entity-name">${open?'▾':'▸'} ${esc(e?.nombre||'Sin entidad')}</div><div class="sub">${ps.length} productos · ${e?.entidad_maestra_id?'✓ Verificada':'Pendiente de verificar'}</div></div><div class="entity-total">${money(ps.reduce((a,p)=>a+val(p),0))}</div></div>${open?'<div class="entity-body">'+productRows(ps)+'</div>':''}</div>`}).join('')+'</div>'}
function categories(){const g={};active().forEach(p=>(g[tn(p)]??=[]).push(p));return '<div class="card"><h2>Categorías</h2>'+Object.entries(g).map(([k,ps])=>`<div class="category"><div class="category-head"><h3>${esc(k)}</h3><div class="sub">${ps.length} productos · ${money(ps.reduce((a,p)=>a+val(p),0))}</div></div>${productRows(ps)}</div>`).join('')+'</div>'}
function summary(){const t=active().reduce((a,p)=>a+val(p),0),a=active().filter(account).reduce((s,p)=>s+val(p),0);return `<div class="hero"><div>Patrimonio total</div><div class="total">${money(t)}</div><div class="stats"><div class="stat">Cuentas<b>${money(a)}</b></div><div class="stat">Inversiones<b>${money(t-a)}</b></div><div class="stat">Productos<b>${active().length}</b></div><div class="stat">Entidades<b>${Object.keys(groups()).length}</b></div></div></div>`}
function inactive(){const ps=S.p.filter(p=>p.activo===false);return '<div class="card"><h2>📁 Inactivos</h2>'+(!ps.length?'<div class="empty">No hay productos inactivos.</div>':ps.map(p=>`<div class="inactive row"><div><b>${esc(p.nombre)}</b><div class="sub">${esc(tn(p))}</div></div><button class="btn alt" onclick="activate('${p.id}')">Reactivar</button></div>`).join(''))+'</div>'}
function sources(){return '<div class="card"><h2>Fuentes de valoración</h2>'+(!S.sources.length?'<div class="empty">No hay fuentes configuradas.</div>':S.sources.map(s=>`<div class="row"><span><b>${esc(s.nombre)}</b><div class="sub">${esc(s.tipo_fuente||'')} · ${s.gratuita?'Gratuita':'De pago'}</div></span><span class="pill ${s.activa?'ok':'warn'}">${s.activa?'Activa':'Inactiva'}</span></div>`).join(''))+'</div>'}
function library(){return '<div class="card"><h2>📚 Biblioteca</h2><div class="section"><div class="section-title">Fuentes</div>'+(!S.sources.length?'<div class="empty">No hay fuentes.</div>':S.sources.map(s=>`<div class="library-item"><b>${esc(s.nombre)}</b><div class="sub">${esc(s.tipo_fuente||'')} · ${s.ofrece_historico?'Histórico disponible':'Sin histórico declarado'} · ${s.tiempo_real?'Tiempo real':'Fin de día / diferido'}</div></div>`).join(''))+'</div><div class="section"><div class="section-title">Documentos de productos</div>'+(!S.docs.length?'<div class="empty">Todavía no hay documentos.</div>':S.docs.map(d=>`<div class="library-item"><b>📎 ${esc(d.archivo_nombre)}</b><div class="sub">${esc(S.p.find(p=>p.id===d.producto_id)?.nombre||'Producto')} · ${date(d.fecha_documento)} · ${esc(d.estado||'')}</div></div>`).join(''))+'</div></div>'}
function interests(){return '<div class="card"><div class="toolbar"><h2>Intereses</h2><button class="btn" onclick="interestForm()">＋ Añadir interés</button></div>'+(!S.i.length?'<div class="empty">No hay intereses registrados.</div>':S.i.map(x=>`<div class="row"><span>${date(x.fecha)} · ${esc(S.p.find(p=>p.id===x.producto_id)?.nombre||'')}</span><span><b>${money(x.importe_neto)}</b> <span class="sub">bruto ${money(x.importe_bruto)} · retención ${money(x.retencion)}</span></span></div>`).join(''))+'</div>'}
function quoteHistory(id){const qh=histQ(id),vh=histV(id),m=new Map();qh.forEach(q=>m.set(String(q.fecha).slice(0,10),{fecha:q.fecha,cot:q.cierre,total:Number(q.cierre||0)*qty(id),origen:'Cotización'}));vh.forEach(v=>{const k=String(v.fecha).slice(0,10),r=m.get(k)||{fecha:v.fecha};r.total=v.valor_total;r.cot=r.cot??v.precio_unitario;r.origen=r.origen?r.origen+' + '+(v.origen||'Valoración'):(v.origen||'Valoración');m.set(k,r)});const rows=[...m.values()].sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));const page=25,start=S.historyPage*page,part=rows.slice(start,start+page);if(!rows.length)return '<div class="empty">Sin histórico.</div>';const body=part.map(r=>`<tr><td>${date(r.fecha)}</td><td>${r.cot==null?'—':num(r.cot)+' €'}</td><td>${r.total==null?'—':money(r.total)}</td><td>${esc(r.origen||'')}</td></tr>`).join('');const prevDisabled=start===0?'disabled':'';const nextDisabled=start+page>=rows.length?'disabled':'';return `<table class="history"><thead><tr><th>Fecha</th><th>Cotización/valor</th><th>Total</th><th>Origen</th></tr></thead><tbody>${body}</tbody></table><div class="toolbar" style="margin-top:12px"><span class="sub">${start+1}-${Math.min(start+page,rows.length)} de ${rows.length}</span><span><button class="btn alt" ${prevDisabled} onclick="S.historyPage--;product('${id}')">Anterior</button> <button class="btn alt" ${nextDisabled} onclick="S.historyPage++;product('${id}')">Siguiente</button></span></div>`}
async function product(id){const p=S.p.find(x=>x.id===id);if(!p)return;S.context=id;S.historyPage=0;try{if(!account(p)&&!S.qLoaded[id])await ensureQuotes(id);const unit=currentUnit(p),c=cost(p),d=diff(p),pc=pct(p);modalBox.innerHTML=`<div class="toolbar"><h2>${esc(p.nombre)}</h2><button class="btn alt" onclick="closeM()">Cerrar</button></div><div class="sub">${esc(en(p))} · ${esc(tn(p))}</div><div class="toolbar" style="margin:15px 0"><button class="btn" onclick="manualData('${id}')">＋ Introducir datos</button><button class="btn alt" onclick="capture('${id}')">📎 Captura / PDF / Word / Excel</button>${account(p)?'':'<button class="btn alt" onclick="operationForm(\''+id+'\')">＋ Operación</button>'}${p.activo!==false?'<button class="btn red" onclick="deactivate(\''+id+'\')">Pasar a inactivos</button>':''}</div>${account(p)?accountHistory(p):`<div class="card"><table class="history"><thead><tr><th>Posición</th><th>Coste</th><th>Coste medio</th><th>Última cotización/valor liquidativo</th><th>Fecha</th><th>Valor actual</th><th>Diferencia</th><th>%</th></tr></thead><tbody><tr><td>${num(qty(id))}</td><td>${c==null?'—':money(c)}</td><td>${c==null||!qty(id)?'—':num(c/qty(id))+' €'}</td><td>${unit==null?'—':num(unit)+' €'}</td><td>${date(currentDate(p))}</td><td>${money(val(p))}</td><td class="${d>0?'gain':d<0?'loss':''}">${d?(d>0?'+':'')+money(d):'—'}</td><td class="${pc>0?'gain':pc<0?'loss':''}">${pc?(pc>0?'+':'')+pc.toFixed(2)+' %':'—'}</td></tr></tbody></table></div>`}<div class="card"><h3>Histórico completo de cotizaciones / valoraciones</h3>${quoteHistory(id)}</div><div class="card"><h3>Operaciones</h3>${opsHistory(id)}</div><div class="card"><h3>Documentos asociados</h3>${docsHistory(id)}</div>`;modal.classList.add('open')}catch(e){alert('No se pudo cargar el histórico: '+(e.message||e))}}
function accountHistory(p){const h=histV(p.id);return '<div class="card"><h3>Histórico de saldos</h3><table class="history"><thead><tr><th>Fecha</th><th>Saldo</th><th>Diferencia</th></tr></thead><tbody>'+h.map((x,i)=>{const prev=h[i+1],d=prev?Number(x.valor_total)-Number(prev.valor_total):null;return `<tr><td>${date(x.fecha)}</td><td>${money(x.valor_total)}</td><td class="${d>0?'gain':d<0?'loss':''}">${d==null?'—':(d>0?'+':'')+money(d)}</td></tr>`}).join('')+'</tbody></table></div>'}
function opsHistory(id){const a=S.o.filter(x=>x.producto_id===id).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));return a.length?'<table class="history"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Precio</th></tr></thead><tbody>'+a.map(x=>`<tr><td>${date(x.fecha)}</td><td>${esc(x.tipo_operacion)}</td><td>${num(x.cantidad)}</td><td>${money(x.precio_unitario)}</td></tr>`).join('')+'</tbody></table>':'<div class="empty">Sin operaciones.</div>'}
function docsHistory(id){const a=S.docs.filter(x=>x.producto_id===id);return a.length?a.map(x=>`<div class="row"><span>📎 ${esc(x.archivo_nombre)}<br><small class="sub">${date(x.fecha_documento)} · ${esc(x.estado)}</small></span></div>`).join(''):'<div class="empty">No hay documentos asociados.</div>'}
function manualData(id){id=id||S.context||'';modalBox.innerHTML=`<h2>Introducir datos manualmente</h2><div class="sub">${id?'Producto seleccionado: '+esc(S.p.find(x=>x.id===id)?.nombre||''):'Selecciona el producto.'}</div><div class="form"><label>Producto<select id="mdp" onchange="manualRefresh()">${active().map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select></label><label>Fecha<input id="mdf" type="date" value="${today()}"></label><div id="manualFields" class="full"></div></div><br><button class="btn" onclick="saveManual()">Guardar</button> <button class="btn alt" onclick="closeM()">Cancelar</button>`;manualRefresh();modal.classList.add('open')}
function manualRefresh(){const p=S.p.find(x=>x.id===$('mdp').value);$('manualFields').innerHTML=account(p)?'<div class="form"><label class="full">Saldo<input id="mdv" type="number" step="0.00000001"></label><label class="full">Observaciones<textarea id="mdo"></textarea></label></div>':'<div class="form"><label>Tipo<select id="mdt"><option value="valoracion">Valoración / valor liquidativo</option><option value="operacion">Operación / aportación</option></select></label><label>Cantidad / participaciones<input id="mdq" type="number" step="0.00000001"></label><label>Precio / valor unitario<input id="mdpu" type="number" step="0.00000001"></label><label>Valor total<input id="mdvt" type="number" step="0.00000001"></label><label class="full">Observaciones<textarea id="mdo"></textarea></label></div>'}
async function saveManual(){const id=$('mdp').value,fecha=$('mdf').value,p=S.p.find(x=>x.id===id);if(account(p)){const r=await db.from('valoraciones_historicas').insert({user_id:S.user.id,producto_id:id,fecha,valor_total:Number($('mdv').value)||0,origen:'Manual',fuente:'Usuario',es_valida:true,prioridad_origen:100,observaciones:$('mdo').value});if(r.error)return alert(r.error.message)}else{const total=Number($('mdvt').value)||Number($('mdq').value)*Number($('mdpu').value);const r=$('mdt').value==='operacion'?await db.from('operaciones').insert({user_id:S.user.id,producto_id:id,fecha,tipo_operacion:'Aportación',cantidad:Number($('mdq').value)||0,precio_unitario:Number($('mdpu').value)||0,importe_neto:total,moneda:'EUR',observaciones:$('mdo').value}):await db.from('valoraciones_historicas').insert({user_id:S.user.id,producto_id:id,fecha,cantidad:Number($('mdq').value)||0,precio_unitario:Number($('mdpu').value)||0,valor_total:total,origen:'Manual',fuente:'Usuario',es_valida:true,prioridad_origen:100,observaciones:$('mdo').value});if(r.error)return alert(r.error.message)}closeM();load()}
function operationForm(id){modalBox.innerHTML=`<h2>Nueva operación</h2><div class="form"><label>Producto<select id="opP">${active().map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select></label><label>Fecha<input id="opF" type="date" value="${today()}"></label><label>Tipo<select id="opT"><option>Compra</option><option>Venta</option><option>Aportación</option><option>Dividendo en acciones</option><option>Acciones liberadas</option><option>Split</option><option>Traspaso</option><option>Ajuste de posición</option><option>Dividendo en efectivo</option><option>Prima de emisión</option><option>Venta de derechos</option></select></label><label>Cantidad<input id="opQ" type="number" step="0.00000001"></label><label>Precio unitario<input id="opPrc" type="number" step="0.00000001"></label><label>Importe neto<input id="opN" type="number" step="0.01"></label><label class="full">Observaciones<textarea id="opO"></textarea></label></div><br><button class="btn" onclick="saveOp()">Guardar</button> <button class="btn alt" onclick="closeM()">Cancelar</button>`;modal.classList.add('open')}
async function saveOp(){const r=await db.from('operaciones').insert({user_id:S.user.id,producto_id:$('opP').value,fecha:$('opF').value,tipo_operacion:$('opT').value,cantidad:Number($('opQ').value)||0,precio_unitario:Number($('opPrc').value)||0,importe_neto:Number($('opN').value)||0,moneda:'EUR',observaciones:$('opO').value});if(r.error)alert(r.error.message);else{closeM();load()}}
function interestForm(){modalBox.innerHTML=`<h2>Añadir interés</h2><div class="form"><label>Cuenta<select id="ip">${S.p.filter(account).map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join('')}</select></label><label>Fecha<input id="ifd" type="date" value="${today()}"></label><label>Bruto<input id="ib" type="number" step="0.01"></label><label>Retención<input id="ir" type="number" step="0.01"></label><label>Neto<input id="inet" type="number" step="0.01"></label><label class="full">Observaciones<textarea id="io"></textarea></label></div><br><button class="btn" onclick="saveInterest()">Guardar</button> <button class="btn alt" onclick="closeM()">Cancelar</button>`;modal.classList.add('open')}
async function saveInterest(){const b=Number($('ib').value)||0,r=Number($('ir').value)||0,n=$('inet').value===''?b-r:Number($('inet').value);const x=await db.from('intereses_cuentas').insert({user_id:S.user.id,producto_id:$('ip').value,fecha:$('ifd').value,importe_bruto:b,retencion:r,importe_neto:n,moneda:'EUR',origen:'Manual',observaciones:$('io').value});if(x.error)alert(x.error.message);else{closeM();load()}}
function capture(id){modalBox.innerHTML=`<h2>📎 Añadir documento al producto</h2><div class="notice">El archivo queda asociado al producto seleccionado y preparado para extraer datos de ese producto. No se modifica la cartera sin confirmación.</div><div class="form"><label>Producto<select id="cp">${active().map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${esc(p.nombre)}</option>`).join('')}</select></label><label>Fecha<input id="cf" type="date" value="${today()}"></label><label class="full">Archivo<input id="file" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv"></label><label class="full">Observaciones<textarea id="co"></textarea></label></div><br><button class="btn" onclick="saveCapture()">Guardar y preparar revisión</button> <button class="btn alt" onclick="closeM()">Cancelar</button>`;modal.classList.add('open')}
async function saveCapture(){const f=$('file').files[0];if(!f)return alert('Selecciona un archivo.');const path=S.user.id+'/'+Date.now()+'_'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await db.storage.from('patrimonio-documentos').upload(path,f,{upsert:false});if(u.error)return alert(u.error.message);const r=await db.from('documentos_capturas').insert({user_id:S.user.id,producto_id:$('cp').value,fecha_documento:$('cf').value,archivo_nombre:f.name,archivo_tipo:f.type,archivo_path:path,estado:'pendiente_revision',datos_detectados:{},datos_confirmados:{},observaciones:$('co').value});if(r.error)alert(r.error.message);else{closeM();load()}}
async function activate(id){const r=await db.from('productos').update({activo:true}).eq('id',id).eq('user_id',S.user.id);if(r.error)alert(r.error.message);else load()}
async function deactivate(id){if(!confirm('¿Pasar este producto a Inactivos?'))return;const r=await db.from('productos').update({activo:false}).eq('id',id).eq('user_id',S.user.id);if(r.error)alert(r.error.message);else{closeM();load()}}
function closeM(){modal.classList.remove('open')}
function render(){const tabs=[['resumen','🏠 Resumen'],['entidades','🏦 Entidades'],['categorias','📊 Categorías'],['biblioteca','📚 Biblioteca'],['inactivos','📁 Inactivos'],['intereses','💶 Intereses'],['fuentes','🌐 Fuentes']];$('app').innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>Patrimonio</h1><p>Tu patrimonio, en un solo lugar</p></div><button class="btn alt" onclick="logout()">Salir</button></div><div class="tabs">${tabs.map(x=>`<button class="tab ${S.tab===x[0]?'active':''}" onclick="S.tab='${x[0]}';render()">${x[1]}</button>`).join('')}</div>${S.tab==='resumen'?summary():S.tab==='entidades'?entities():S.tab==='categorias'?categories():S.tab==='biblioteca'?library():S.tab==='inactivos'?inactive():S.tab==='intereses'?interests():sources()}</div>`}
window.addEventListener('error',e=>{const a=$('app');if(a)a.innerHTML='<div class="wrap"><div class="card error"><h2>Error de JavaScript</h2><p>'+esc(e.message||'Error desconocido')+'</p></div></div>'});load();