(function(){'use strict';
const MONTHS={ene:1,enero:1,feb:2,febrero:2,mar:3,marzo:3,abr:4,abril:4,may:5,mayo:5,jun:6,junio:6,jul:7,julio:7,ago:8,agosto:8,sep:9,sept:9,set:9,septiembre:9,oct:10,octubre:10,nov:11,noviembre:11,dic:12,diciembre:12};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
function num(s){let x=String(s??'').replace(/[Oo]/g,'0').replace(/[Il|]/g,'1').replace(/[Ss]/g,'5').replace(/[€$]/g,'').replace(/\s/g,'').replace(/[^0-9,.\-]/g,'');if(!x)return null;let c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>=0&&d>=0){if(c>d)x=x.replace(/\./g,'').replace(',','.');else x=x.replace(/,/g,'')}else if(c>=0)x=x.replace(',','.');else if((x.match(/\./g)||[]).length>1)x=x.replace(/\./g,'');let v=Number(x);return Number.isFinite(v)?v:null}
function date(s){let x=norm(s).replace(/\./g,'');let m=x.match(/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/);if(m&&MONTHS[m[2]])return `${m[3]}-${String(MONTHS[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=x.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return null}
function findDate(words){let s=words.map(w=>w.text).join(' '),m=s.match(/(\d{1,2})\s*([a-záéíóúñ]+)\s*(\d{4})/i);if(m&&MONTHS[norm(m[2])])return date(m[1]+' '+m[2]+' '+m[3]);m=s.match(/(\d{1,2})\s*[\/-]\s*(\d{1,2})\s*[\/-]\s*(\d{2,4})/);if(m)return date(m[1]+'/'+m[2]+'/'+m[3]);return null}
function wordNum(text){let v=num(text);return v!=null&&v>=0&&v<1000000?v:null}
function groupRows(words){let ws=words.filter(w=>String(w.text||'').trim()&&Number(w.conf??0)>=15).map(w=>({...w,cx:w.left+w.width/2,cy:w.top+w.height/2})).sort((a,b)=>a.cy-b.cy),rows=[];for(const w of ws){let r=rows.find(r=>Math.abs(r.cy-w.cy)<=Math.max(8,w.height*.7));if(!r){r={cy:w.cy,words:[]};rows.push(r)}r.words.push(w);r.cy=r.words.reduce((a,x)=>a+x.cy,0)/r.words.length}return rows.sort((a,b)=>a.cy-b.cy)}
function headerCenters(words){let h={};for(const w of words){let t=norm(w.text);if(t==='bruto'&&!h.g)h.g=w.left+w.width/2;if((t==='retencion'||t==='retención')&&!h.r)h.r=w.left+w.width/2;if(t==='neto'&&!h.n)h.n=w.left+w.width/2}return h}
function parseMoneyTokens(words){let out=[];for(const w of words){let t=String(w.text||'').trim();if(!/[0-9OoIl|]/.test(t))continue;let v=wordNum(t);if(v==null||[2024,2025,2026].includes(v))continue;out.push({v,x:w.cx})}return out}
function chooseByColumns(vals,h){let centers=[h.g,h.r,h.n];if(centers.some(x=>x==null)){let xs=vals.map(x=>x.x).sort((a,b)=>a-b);if(xs.length<3)return null;centers=[xs[0],xs[Math.floor(xs.length/2)],xs[xs.length-1]]}let picked=[null,null,null],used=new Set();for(let j=0;j<3;j++){let best=null;for(let i=0;i<vals.length;i++){if(used.has(i))continue;let d=Math.abs(vals[i].x-centers[j]);if(!best||d<best.d)best={i,d}}if(best){picked[j]=vals[best.i];used.add(best.i)}}return picked.some(x=>!x)?null:picked}
function parseTsv(data){let words=data.words||[],h=headerCenters(words),out=[];for(const row of groupRows(words)){let fecha=findDate(row.words);if(!fecha)continue;let vals=parseMoneyTokens(row.words);if(vals.length<3)continue;let p=chooseByColumns(vals,h);if(!p)continue;let g=p[0].v,r=Math.abs(p[1].v),n=p[2].v;if(Math.abs((g-r)-n)<=0.08)out.push({fecha,importe_bruto:g,retencion:r,importe_neto:n})}return dedupe(out)}
function dedupe(rows){let s=new Set(),o=[];for(const r of rows){let k=`${r.fecha}|${r.importe_bruto.toFixed(2)}|${r.retencion.toFixed(2)}|${r.importe_neto.toFixed(2)}`;if(!s.has(k)){s.add(k);o.push(r)}}return o.sort((a,b)=>a.fecha.localeCompare(b.fecha))}
async function lib(src){return new Promise((ok,no)=>{let s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function preprocess(file){return new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{let scale=Math.max(2,Math.min(3,2800/Math.max(im.width,im.height))),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);let x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,c.width,c.height);let d=x.getImageData(0,0,c.width,c.height),p=d.data;for(let i=0;i<p.length;i+=4){let y=.299*p[i]+.587*p[i+1]+.114*p[i+2];y=y<170?0:255;p[i]=p[i+1]=p[i+2]=y}x.putImageData(d,0,0);resolve(c.toDataURL('image/png'))};im.onerror=reject;im.src=URL.createObjectURL(file)})}
async function ocrImage(file){if(!window.Tesseract)await lib('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');let sources=[file];try{sources.push(await preprocess(file))}catch(_){}let all=[];for(let si=0;si<sources.length;si++)for(const psm of ['6','11']){try{let r=await Tesseract.recognize(sources[si],'spa+eng',{logger:m=>{if(m.status==='recognizing text'&&typeof m.progress==='number')setStatus(`Leyendo tabla por columnas… ${Math.round(m.progress*100)} %`)},config:{tessedit_pageseg_mode:psm,preserve_interword_spaces:'1'}});all.push(...parseTsv(r.data))}catch(_){} }return dedupe(all)}
function fmt(v){return Number(v).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})}
function valid(r){return/^\d{4}-\d{2}-\d{2}$/.test(r.fecha)&&Number.isFinite(+r.importe_bruto)&&Number.isFinite(+r.retencion)&&Number.isFinite(+r.importe_neto)&&+r.importe_bruto>=0&&+r.retencion>=0&&+r.importe_neto>=0&&Math.abs((+r.importe_bruto-+r.retencion)-+r.importe_neto)<=0.08}
function injectStyle(){if(document.getElementById('ii2ocrstyle'))return;let s=document.createElement('style');s.id='ii2ocrstyle';s.textContent='.ii2edit{width:100%;min-width:105px;padding:8px 9px;border:1px solid #c8d8eb;border-radius:8px;background:#fff;color:#17243d;text-align:right}.ii2edit[type=date]{text-align:left;min-width:145px}.ii2p tr.bad{background:#fff3f1}.ii2p tr.bad .ii2edit{border-color:#e39a92;background:#fff9f8}.ii2del{border:0;border-radius:8px;padding:8px 9px;background:#f3f6fa;color:#234b86;font-weight:800;cursor:pointer}.ii2hint{padding:10px 12px;color:#71809a;font-size:12px}.ii2p td{vertical-align:middle}';document.head.appendChild(s)}
function refreshRow(tr,r){if(tr)tr.classList.toggle('bad',!valid(r))}
function updateSaveState(){let b=document.getElementById('ii2save'),rows=window.II2ROWS||[];if(b)b.disabled=!rows.length||rows.some(r=>!valid(r))}
function renderPreview(rows){injectStyle();let e=document.getElementById('ii2prev'),b=document.getElementById('ii2save');if(!e)return;if(!rows.length){e.innerHTML='<div class="ii2err">No se han podido leer filas válidas. No se guardará ningún dato inventado por el OCR.</div>';if(b)b.disabled=true;return}e.innerHTML=`<div class="ii2p"><table><thead><tr><th>Fecha</th><th>Bruto</th><th>Retención</th><th>Neto</th><th></th></tr></thead><tbody>${rows.map((r,i)=>`<tr data-i="${i}"><td><input class="ii2edit" data-k="fecha" value="${esc(r.fecha)}" type="date"></td><td><input class="ii2edit" data-k="importe_bruto" value="${fmt(r.importe_bruto)}"></td><td><input class="ii2edit" data-k="retencion" value="${fmt(r.retencion)}"></td><td><input class="ii2edit" data-k="importe_neto" value="${fmt(r.importe_neto)}"></td><td><button type="button" class="ii2del" data-del="${i}">Eliminar</button></td></tr>`).join('')}</tbody></table><div class="ii2hint">Puedes corregir cualquier dato directamente antes de guardar. Una fila incorrecta queda marcada y no se puede guardar hasta corregirla.</div></div>`;e.querySelectorAll('.ii2edit').forEach(inp=>inp.addEventListener('input',()=>{let tr=inp.closest('tr'),i=+tr.dataset.i,k=inp.dataset.k;window.II2ROWS[i][k]=k==='fecha'?inp.value:num(inp.value);refreshRow(tr,window.II2ROWS[i]);updateSaveState()}));e.querySelectorAll('.ii2del').forEach(btn=>btn.onclick=()=>{window.II2ROWS.splice(+btn.dataset.del,1);renderPreview(window.II2ROWS)});rows.forEach((r,i)=>refreshRow(e.querySelector(`tr[data-i="${i}"]`),r));updateSaveState()}
function setStatus(t){let e=document.getElementById('ii2status');if(e)e.textContent=t}
async function load(){let i=document.getElementById('ii2file');if(!i?.files?.[0])return;let f=i.files[0],ext=(f.name.split('.').pop()||'').toLowerCase();try{if(f.type.startsWith('image/')||['jpg','jpeg','png','webp'].includes(ext)){setStatus('Leyendo la captura por columnas…');let rows=await ocrImage(f);window.II2ROWS=rows;renderPreview(rows);setStatus(rows.length?`Detectados ${rows.length} movimientos. Revisa y corrige la vista previa antes de guardar.`:'No se detectaron filas válidas.')}else setStatus('El archivo no es una imagen; se utilizará el importador estructurado correspondiente.')}catch(e){setStatus('No se pudo leer la captura: '+(e.message||e))}}
async function save(){let rows=(window.II2ROWS||[]).filter(valid),pid=document.getElementById('ii2a')?.value;if(!rows.length||!pid)return;let b=document.getElementById('ii2save');b.disabled=true;try{let ex=await db.from('intereses_cuentas').select('fecha,importe_bruto,retencion,importe_neto').eq('user_id',S.user.id).eq('producto_id',pid);if(ex.error)throw ex.error;let key=x=>`${String(x.fecha).slice(0,10)}|${Number(x.importe_bruto).toFixed(2)}|${Number(x.retencion||0).toFixed(2)}|${Number(x.importe_neto).toFixed(2)}`,known=new Set((ex.data||[]).map(key)),data=rows.filter(x=>!known.has(key(x))).map(x=>({user_id:S.user.id,producto_id:pid,fecha:x.fecha,importe_bruto:x.importe_bruto,retencion:x.retencion,importe_neto:x.importe_neto,moneda:'EUR',origen:'importado',observaciones:'Importado desde captura/PDF/Word/Excel/CSV/TXT'}));if(!data.length){setStatus('No hay movimientos nuevos; los movimientos ya están registrados.');return}let ins=await db.from('intereses_cuentas').insert(data);if(ins.error)throw ins.error;S.i=(S.i||[]).concat(data);setStatus('Guardados '+data.length+' movimientos.');setTimeout(()=>{document.getElementById('ii2m')?.classList.remove('on');render()},500)}catch(e){setStatus('No se pudieron guardar los intereses: '+(e.message||e))}finally{b.disabled=false}}
function hook(){let i=document.getElementById('ii2file');if(i&&!i.dataset.ocrFix){i.dataset.ocrFix='3';i.onchange=load}let b=document.getElementById('ii2save');if(b&&!b.dataset.ocrSaveFix){b.dataset.ocrSaveFix='3';b.onclick=save}}
let tries=0,timer=setInterval(()=>{hook();if(++tries>240)clearInterval(timer)},250);
})();