(function(){'use strict';
const months={ene:1,enero:1,feb:2,febrero:2,mar:3,marzo:3,abr:4,abril:4,may:5,mayo:5,jun:6,junio:6,jul:7,julio:7,ago:8,agosto:8,sep:9,sept:9,septiembre:9,oct:10,octubre:10,nov:11,noviembre:11,dic:12,diciembre:12};
const n=s=>{let x=String(s??'').replace(/[^0-9,.-]/g,'');if(!x)return null;let c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>d)x=x.replace(/\./g,'').replace(',','.');else if(d>c)x=x.replace(/,/g,'');let v=Number(x);return Number.isFinite(v)?v:null};
function date(s){let x=String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(),m=x.match(/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/);if(m&&months[m[2]])return`${m[3]}-${String(months[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=x.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return null}
function parseLine(line){let x=String(line||'').replace(/[|;]/g,' ').replace(/\s+/g,' ').trim();let dm=x.match(/^(\d{1,2}\s+[A-Za-zñ]+\s+\d{4}|\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})\b/i);if(!dm)return null;let fecha=date(dm[1]);if(!fecha)return null;let tail=x.slice(dm[0].length);let nums=(tail.match(/[-+]?\d{1,3}(?:\.\d{3})*,\d+|[-+]?\d+(?:[.,]\d+)/g)||[]).map(n).filter(v=>v!=null);if(nums.length<3)return null;let best=null;for(let i=0;i<=nums.length-3;i++){let g=nums[i],r=Math.abs(nums[i+1]),net=nums[i+2];if(Math.abs((g-r)-net)<=0.03){best={fecha,importe_bruto:g,retencion:r,importe_neto:net};break}}return best||{fecha,importe_bruto:nums[0],retencion:Math.abs(nums[1]),importe_neto:nums[2]};}
function status(t){let e=document.getElementById('ii2status');if(e)e.textContent=t}
function preview(rows){let e=document.getElementById('ii2prev'),b=document.getElementById('ii2save');if(!e)return;if(!rows.length){e.innerHTML='<div class="ii2err">No se han detectado filas de intereses. La imagen debe mostrar fecha y los importes bruto, retención y neto.</div>';if(b)b.disabled=true;return}e.innerHTML='<div class="ii2p"><table><thead><tr><th>Fecha</th><th>Bruto</th><th>Retención</th><th>Neto</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r.fecha}</td><td>${r.importe_bruto.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${r.retencion.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${r.importe_neto.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td></tr>`).join('')+'</tbody></table></div>';if(b)b.disabled=false}
async function load(){if(!window.Tesseract){await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}let input=document.getElementById('ii2file');if(!input||!input.files[0])return;let f=input.files[0];if(!f.type.startsWith('image/'))return;status('Reconociendo la tabla de intereses…');try{let r=await Tesseract.recognize(f,'spa+eng');let rows=r.data.text.split(/\r?\n/).map(parseLine).filter(Boolean);window.II2ROWS=rows;preview(rows);status(rows.length?`Detectados ${rows.length} movimientos. Revisa la vista previa antes de guardar.`:'No se detectaron movimientos.');}catch(e){status('No se pudo leer la captura: '+(e.message||e));}}
function hook(){let i=document.getElementById('ii2file');if(!i||i.dataset.ocrFix)return;i.dataset.ocrFix='1';i.onchange=load}
let tries=0;let timer=setInterval(()=>{hook();if(++tries>120)clearInterval(timer)},250);})();