(function(){
'use strict';
const CSS=`
#ii-style{display:none}.ii-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.ii-btn{border:1px solid #c8d8eb;background:#f7fbff;color:#234b86;border-radius:11px;padding:9px 13px;font-weight:800;cursor:pointer}.ii-btn.primary{background:#234b86;color:#fff}.ii-modal{position:fixed;inset:0;background:#09152a99;display:none;align-items:center;justify-content:center;padding:14px;z-index:120}.ii-modal.open{display:flex}.ii-box{background:#fff;width:min(980px,100%);max-height:94vh;overflow:auto;border-radius:20px;padding:20px;box-shadow:0 20px 60px #09152a33}.ii-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ii-field label{display:block;font-size:12px;font-weight:800;color:#536581}.ii-field input,.ii-field select{width:100%;margin-top:5px;border:1px solid #d9e2ee;border-radius:10px;padding:10px;background:#fff}.ii-drop{border:2px dashed #b9cde4;border-radius:16px;padding:24px;text-align:center;background:#f7fbff;margin:12px 0}.ii-drop strong{display:block;font-size:18px;color:#234b86}.ii-help{color:#71809a;font-size:13px;margin:6px 0}.ii-preview{overflow:auto;margin-top:12px;border:1px solid #d9e2ee;border-radius:12px}.ii-preview table{width:100%;border-collapse:collapse;min-width:620px}.ii-preview th,.ii-preview td{padding:8px;border-bottom:1px solid #d9e2ee;text-align:right;white-space:nowrap}.ii-preview th:first-child,.ii-preview td:first-child{text-align:left}.ii-ok{color:#16834b;font-weight:800}.ii-warn{color:#8a6919;background:#fff7df;border-radius:10px;padding:10px}.ii-error{color:#c43b32;background:#fff0ef;border-radius:10px;padding:10px}.ii-foot{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.ii-close{border:0;background:#eef3f9;color:#234b86;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}
@media(max-width:600px){.ii-grid{grid-template-columns:1fr}.ii-box{padding:14px;border-radius:16px}.ii-drop{padding:18px}.ii-actions{display:grid;grid-template-columns:1fr 1fr}.ii-btn{width:100%}}
`;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function norm(s){return String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function moneyNum(s){if(typeof s==='number')return s;let x=String(s??'').replace(/[^0-9,.-]/g,'').trim();if(!x)return null;let c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>d)x=x.replace(/\./g,'').replace(',','.');else if(d>c)x=x.replace(/,/g,'');else x=x.replace(',','.');let n=Number(x);return Number.isFinite(n)?n:null}
function parseDate(s){if(s instanceof Date&&!isNaN(s))return s.toISOString().slice(0,10);if(typeof s==='number'&&s>20000&&s<70000){let d=new Date(Date.UTC(1899,11,30)+s*86400000);return d.toISOString().slice(0,10)}let x=String(s??'').trim();if(!x)return null;let m=x.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return `${y.toString().padStart(4,'0')}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}m=x.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function loadScript(src){return new Promise((res,rej)=>{let s=document.querySelector('script[data-ii-lib="'+src+'"]');if(s)return s.dataset.loaded==='1'?res():s.addEventListener('load',res,{once:true});s=document.createElement('script');s.src=src;s.dataset.iiLib=src;s.onload=()=>{s.dataset.loaded='1';res()};s.onerror=rej;document.head.appendChild(s)})}
async function parseFile(file){let ext=(file.name.split('.').pop()||'').toLowerCase();if(file.type.startsWith('image/')||['png','jpg','jpeg','webp','heic'].includes(ext)){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');let r=await Tesseract.recognize(file,'spa+eng',{logger:m=>{if(window.II_STATUS&&m.progress)window.II_STATUS(Math.round(m.progress*100)+'%')}});return textToRows(r.data.text)}if(ext==='pdf'||file.type==='application/pdf'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');let pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,txt='';for(let i=1;i<=pdf.numPages;i++){let p=await pdf.getPage(i),c=await p.getTextContent();txt+=c.items.map(x=>x.str).join(' ')+'\n'}return textToRows(txt)}if(['xlsx','xls'].includes(ext)||file.type.includes('spreadsheet')){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');let wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});let sh=wb.Sheets[wb.SheetNames[0]];return sheetToRows(XLSX.utils.sheet_to_json(sh,{header:1,defval:''}))}if(['docx','doc'].includes(ext)||file.type.includes('wordprocessing')){await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js');let r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return textToRows(r.value)}if(['csv','txt'].includes(ext)||file.type.startsWith('text/'))return textToRows(await file.text());throw new Error('Formato no compatible. Usa captura/imagen, PDF, Word, Excel, CSV o TXT.')}
function sheetToRows(rows){if(!rows.length)return[];let h=rows[0].map(norm);let di=findCol(h,['fecha','date','dia']);let gi=findCol(h,['importe bruto','bruto','interes bruto','intereses','importe']);let ri=findCol(h,['retencion','retenciones','withholding','irpf']);let ni=findCol(h,['importe neto','neto','interes neto']);let out=[];for(let i=1;i<rows.length;i++){let r=rows[i];let date=parseDate(r[di]),gross=moneyNum(r[gi]),ret=moneyNum(r[ri])||0,net=moneyNum(r[ni]);if(date&&gross!=null)out.push({fecha:date,importe_bruto:gross,retencion:ret,importe_neto:net==null?gross-ret:net})}return out}
function findCol(h,names){for(let n of names){let i=h.findIndex(x=>x===n||x.includes(n));if(i>=0)return i}return -1}
function textToRows(txt){let lines=String(txt||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];for(let line of lines){let m=line.match(/(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{4}[\/-]\d{1,2}[\/-]\d{1,2})/);if(!m)continue;let date=parseDate(m[1]),rest=line.slice(m.index+m[1].length);let nums=(rest.match(/-?\d[\d.]*[\d](?:,\d+)?|-?\d+(?:[,.]\d+)/g)||[]).map(moneyNum).filter(x=>x!=null);if(date&&nums.length){let gross=nums.length>=3?nums[0]:nums[0],ret=nums.length>=3?Math.abs(nums[1]):0,net=nums.length>=3?nums[2]:(nums.length>=2?nums[1]:gross-ret);if(gross!=null)out.push({fecha:date,importe_bruto:gross,retencion:ret,importe_neto:net})}}return out}
function accounts(){return (window.S?.p||[]).filter(p=>window.account?.(p)).sort((a,b)=>String(a.nombre).localeCompare(String(b.nombre)))}
function openModal(){let a=accounts();let m=document.getElementById('ii-modal');if(!m){m=document.createElement('div');m.id='ii-modal';m.className='ii-modal';m.innerHTML='<div class="ii-box"><div class="toolbar"><div><h2 style="margin:0">Añadir intereses</h2><div class="ii-help">Importa intereses desde una captura, PDF, Word, Excel, CSV o TXT.</div></div><button class="ii-close" id="ii-x">Cerrar</button></div><div class="ii-grid" style="margin-top:14px"><div class="ii-field"><label>Cuenta<select id="ii-account">'+a.map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join('')+'</select></label></div><div class="ii-field"><label>Archivo<input id="ii-file" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt" capture="environment"></label></div></div><div class="ii-drop"><strong>📷 Captura · 📄 PDF · 📝 Word · 📊 Excel</strong><div class="ii-help">En móvil puedes usar directamente la cámara para fotografiar el extracto.</div><button class="ii-btn primary" id="ii-select">Seleccionar archivo</button></div><div id="ii-status" class="ii-help"></div><div id="ii-result"></div><div class="ii-foot"><button class="ii-close" id="ii-cancel">Cancelar</button><button class="ii-btn primary" id="ii-save" disabled>Guardar intereses</button></div></div>';document.body.appendChild(m);m.querySelector('#ii-x').onclick=m.querySelector('#ii-cancel').onclick=()=>m.classList.remove('open');m.querySelector('#ii-select').onclick=()=>m.querySelector('#ii-file').click();m.querySelector('#ii-file').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;status('Procesando '+f.name+'…');window.II_STATUS=x=>status('Procesando documento… '+x);let rows=await parseFile(f);window.II_ROWS=rows;renderPreview(rows);status(rows.length?`Detectados ${rows.length} movimientos.`:'No se detectaron filas. Puedes probar otra captura o archivo.');}catch(err){status('<div class="ii-error">'+esc(err.message||err)+'</div>',true)}};m.querySelector('#ii-save').onclick=save;}
let a=document.getElementById('ii-account');if(a&&accounts().length&&!a.value)a.value=accounts()[0].id;m.classList.add('open')}
function status(x,raw){let el=document.getElementById('ii-status');if(el)el.innerHTML=raw?x:esc(x)}
function renderPreview(rows){let r=document.getElementById('ii-result'),save=document.getElementById('ii-save');if(!r)return;window.II_ROWS=rows||[];if(!rows?.length){r.innerHTML='<div class="ii-warn">No se han podido reconocer datos de intereses. Comprueba que la fecha y los importes sean legibles.</div>';save.disabled=true;return}r.innerHTML='<div class="ii-preview"><table><thead><tr><th>Fecha</th><th>Bruto</th><th>Retención</th><th>Neto</th></tr></thead><tbody>'+rows.slice(0,100).map(x=>`<tr><td>${esc(x.fecha)}</td><td>${Number(x.importe_bruto).toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${Number(x.retencion||0).toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${Number(x.importe_neto||0).toLocaleString('es-ES',{minimumFractionDigits:2})} €</td></tr>`).join('')+'</tbody></table></div>'+(rows.length>100?'<div class="ii-help">Se muestran las primeras 100 filas; se guardarán todas las detectadas.</div>':'');save.disabled=false}
async function save(){let rows=window.II_ROWS||[],pid=document.getElementById('ii-account')?.value;if(!rows.length||!pid)return;let u=window.S?.user;if(!u){status('<div class="ii-error">No hay sesión iniciada.</div>',true);return}let save=document.getElementById('ii-save');save.disabled=true;try{let existing=await window.db.from('intereses_cuentas').select('fecha').eq('user_id',u.id).eq('producto_id',pid);if(existing.error)throw existing.error;let dates=new Set((existing.data||[]).map(x=>String(x.fecha).slice(0,10)));let data=rows.filter(x=>!dates.has(x.fecha)).map(x=>({user_id:u.id,producto_id:pid,fecha:x.fecha,importe_bruto:Number(x.importe_bruto)||0,retencion:Number(x.retencion)||0,importe_neto:Number(x.importe_neto)||0,moneda:'EUR',origen:'importado',observaciones:'Importado desde captura/PDF/Word/Excel/CSV/TXT'}));if(!data.length){status('No había movimientos nuevos: las fechas ya existen.');save.disabled=false;return}let ins=await window.db.from('intereses_cuentas').insert(data);if(ins.error)throw ins.error;window.S.i=(window.S.i||[]).concat(data);status('Guardados '+data.length+' movimientos de intereses.');setTimeout(()=>{document.getElementById('ii-modal')?.classList.remove('open');window.render?.()},700)}catch(e){status('<div class="ii-error">'+esc(e.message||e)+'</div>',true)}finally{save.disabled=false}}
function inject(){if(!window.render||document.getElementById('ii-style'))return;let st=document.createElement('style');st.id='ii-style';st.textContent=CSS;document.head.appendChild(st);let obs=new MutationObserver(()=>{let app=document.getElementById('app');if(!app||document.querySelector('.ii-actions'))return;let nodes=[...app.querySelectorAll('h1,h2,h3')],target=nodes.find(n=>norm(n.textContent).includes('intereses'));if(!target)return;let host=target.closest('.card,.section')||target.parentElement;if(!host)return;let box=document.createElement('div');box.className='ii-actions';box.innerHTML='<button class="ii-btn primary" type="button">＋ Añadir intereses</button><button class="ii-btn" type="button">📷 Captura / documento</button>';box.children[0].onclick=openModal;box.children[1].onclick=openModal;target.insertAdjacentElement('afterend',box)});obs.observe(document.body,{subtree:true,childList:true});setTimeout(()=>obs.takeRecords(),0)}
let tries=0;(function wait(){if(window.S&&window.render&&window.db){inject()}else if(tries++<120)setTimeout(wait,250)})();
window.InteresesImport={open:openModal};
})();
