(function(){'use strict';
const MONTHS={ene:1,enero:1,feb:2,febrero:2,mar:3,marzo:3,abr:4,abril:4,may:5,mayo:5,jun:6,junio:6,jul:7,julio:7,ago:8,agosto:8,sep:9,sept:9,set:9,septiembre:9,oct:10,octubre:10,nov:11,noviembre:11,dic:12,diciembre:12};
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[|;]/g,' ').replace(/\s+/g,' ').trim();
function num(s){let x=String(s??'').replace(/[Oo]/g,'0').replace(/[Il|]/g,'1').replace(/[$€]/g,'').replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!x)return null;let c=x.lastIndexOf(','),d=x.lastIndexOf('.');if(c>d)x=x.replace(/\./g,'').replace(',','.');else if(d>c)x=x.replace(/,/g,'');let v=Number(x);return Number.isFinite(v)?v:null}
function date(s){let x=norm(s).replace(/\./g,'');let m=x.match(/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/);if(m&&MONTHS[m[2]])return `${m[3]}-${String(MONTHS[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=x.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}m=x.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
const DATE_RE=/(\d{1,2}\s+[A-Za-zñÑáéíóúÁÉÍÓÚ.]+\s+\d{4}|\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{4}[\/-]\d{1,2}[\/-]\d{1,2})/i;
function parseLine(line){let x=String(line||'').replace(/(\d)\s*([,.])\s*(\d)/g,'$1$2$3').replace(/\s+/g,' ').trim(),m=x.match(DATE_RE);if(!m)return null;let fecha=date(m[1]);if(!fecha)return null;let tail=x.slice((m.index||0)+m[0].length),tokens=(tail.match(/[-+]?(?:[0-9OoIl|]{1,3}(?:[.,][0-9OoIl|]{3})+|[0-9OoIl|]+)(?:[.,][0-9OoIl|]+)?/g)||[]),vals=tokens.map(num).filter(v=>v!=null);if(vals.length<2)return null;let best=null;for(let i=0;i<=vals.length-3;i++){let g=vals[i],r=Math.abs(vals[i+1]),net=vals[i+2];if(Math.abs((g-r)-net)<=0.05){best={fecha,importe_bruto:g,retencion:r,importe_neto:net};break}}if(!best){let g=vals[0],r=vals.length>=3?Math.abs(vals[1]):0,net=vals.length>=3?vals[2]:vals[1];best={fecha,importe_bruto:g,retencion:r,importe_neto:net}}return best}
function parseText(txt){let out=[];for(const line of String(txt||'').split(/\r?\n/)){let r=parseLine(line);if(r)out.push(r)}let seen=new Set();return out.filter(r=>{let k=`${r.fecha}|${r.importe_bruto.toFixed(2)}|${r.retencion.toFixed(2)}|${r.importe_neto.toFixed(2)}`;if(seen.has(k))return false;seen.add(k);return true})}
function setStatus(t){let e=document.getElementById('ii2status');if(e)e.textContent=t}
function preview(rows){let e=document.getElementById('ii2prev'),b=document.getElementById('ii2save');if(!e)return;if(!rows.length){e.innerHTML='<div class="ii2err">No se han detectado filas de intereses. La imagen debe mostrar fecha y los importes bruto, retención y neto.</div>';if(b)b.disabled=true;return}e.innerHTML='<div class="ii2p"><table><thead><tr><th>Fecha</th><th>Bruto</th><th>Retención</th><th>Neto</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r.fecha}</td><td>${r.importe_bruto.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${r.retencion.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td><td>${r.importe_neto.toLocaleString('es-ES',{minimumFractionDigits:2})} €</td></tr>`).join('')+'</tbody></table></div>';if(b)b.disabled=false}
async function preprocess(file){return new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{let scale=Math.max(2,Math.min(3,2400/Math.max(im.width,im.height))),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);let x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,c.width,c.height);let d=x.getImageData(0,0,c.width,c.height),p=d.data;for(let i=0;i<p.length;i+=4){let y=.299*p[i]+.587*p[i+1]+.114*p[i+2];y=y<150?0:255;p[i]=p[i+1]=p[i+2]=y}x.putImageData(d,0,0);resolve(c.toDataURL('image/png'))};im.onerror=reject;im.src=URL.createObjectURL(file)})}
async function ocr(file){if(!window.Tesseract){await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}let sources=[file];try{sources.push(await preprocess(file))}catch(_){}let all=[];for(let i=0;i<sources.length;i++){setStatus(i?'Analizando la captura con una segunda lectura…':'Reconociendo la tabla de intereses…');for(const mode of ['6','11']){try{let r=await Tesseract.recognize(sources[i],'spa',{logger:m=>{if(m.status==='recognizing text'&&typeof m.progress==='number')setStatus(`Reconociendo la tabla de intereses… ${Math.round(m.progress*100)} %`)},config:{tessedit_pageseg_mode:mode}});all.push(...parseText(r.data.text))}catch(_){} }}let seen=new Set();return all.filter(r=>{let k=`${r.fecha}|${r.importe_bruto.toFixed(2)}|${r.retencion.toFixed(2)}|${r.importe_neto.toFixed(2)}`;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.fecha.localeCompare(b.fecha))}
async function load(){let i=document.getElementById('ii2file');if(!i||!i.files[0])return;let f=i.files[0];if(!f.type.startsWith('image/'))return;try{let rows=await ocr(f);window.II2ROWS=rows;preview(rows);setStatus(rows.length?`Detectados ${rows.length} movimientos. Revisa la vista previa antes de guardar.`:'No se detectaron movimientos. Revisa que la captura incluya fecha, bruto, retención y neto.')}catch(e){setStatus('No se pudo leer la captura: '+(e.message||e))}}
async function save(){let rows=window.II2ROWS||[],pid=document.getElementById('ii2a')?.value;if(!rows.length||!pid)return;let b=document.getElementById('ii2save');b.disabled=true;try{let ex=await db.from('intereses_cuentas').select('fecha,importe_bruto,retencion,importe_neto').eq('user_id',S.user.id).eq('producto_id',pid);if(ex.error)throw ex.error;let key=x=>`${String(x.fecha).slice(0,10)}|${Number(x.importe_bruto).toFixed(2)}|${Number(x.retencion||0).toFixed(2)}|${Number(x.importe_neto).toFixed(2)}`,known=new Set((ex.data||[]).map(key)),data=rows.filter(x=>!known.has(key(x))).map(x=>({user_id:S.user.id,producto_id:pid,fecha:x.fecha,importe_bruto:x.importe_bruto,retencion:x.retencion,importe_neto:x.importe_neto,moneda:'EUR',origen:'importado',observaciones:'Importado desde captura/PDF/Word/Excel/CSV/TXT'}));if(!data.length){setStatus('No hay movimientos nuevos; los movimientos ya están registrados.');return}let ins=await db.from('intereses_cuentas').insert(data);if(ins.error)throw ins.error;S.i=(S.i||[]).concat(data);setStatus('Guardados '+data.length+' movimientos.');setTimeout(()=>{document.getElementById('ii2m')?.classList.remove('on');render()},500)}catch(e){setStatus('No se pudieron guardar los intereses: '+(e.message||e))}finally{b.disabled=false}}
function hook(){let i=document.getElementById('ii2file');if(i&&!i.dataset.ocrFix){i.dataset.ocrFix='2';i.onchange=load}let b=document.getElementById('ii2save');if(b&&!b.dataset.ocrSaveFix){b.dataset.ocrSaveFix='2';b.onclick=save}}
let tries=0;let timer=setInterval(()=>{hook();if(++tries>240)clearInterval(timer)},250);})();
