function historyImporter(){const ps=active().filter(p=>!account(p));const def=S.p.find(p=>p.id===S.context)||ps[0];return '<div class="card"><h2>📥 Históricos de cotizaciones</h2><div class="notice">Ahora puedes recuperar directamente el histórico diario desde Yahoo Finance. Se utiliza el precio <b>Close</b> y se conservan los datos que ya existan.</div><div class="form"><label>Producto<select id="impP">'+ps.map(p=>'<option value="'+p.id+'" '+(p.id===def?.id?'selected':'')+'>'+esc(p.nombre)+(p.ticker?' · '+esc(p.ticker):'')+'</option>').join('')+'</select></label><label>Desde<input id="impFrom" type="date" value="2021-01-01"></label><label>Hasta<input id="impTo" type="date" value="'+today()+'"></label><label>Archivo CSV (opcional)<input id="impFile" type="file" accept=".csv,text/csv"></label></div><div style="margin-top:14px;display:flex;gap:10px;flex-wrap:wrap"><button class="btn" onclick="importYahooHistory()">☁️ Recuperar desde Yahoo</button><button class="btn alt" onclick="importHistoryCsv()">📄 Importar CSV</button></div><div id="impResult" class="sub" style="margin-top:12px"></div></div>'}
async function importYahooHistory(){const pid=$('impP').value,p=S.p.find(x=>x.id===pid),out=$('impResult'),start=$('impFrom').value,end=$('impTo').value;if(!p?.ticker)return out.textContent='Este producto no tiene ticker configurado.';if(!start||!end||start>end)return out.textContent='Revisa las fechas.';out.textContent='Recuperando histórico de '+p.ticker+'…';try{const r=await db.functions.invoke('sync-yahoo-history',{body:{ticker:p.ticker,start,end}});if(r.error)throw r.error;const rows=r.data?.rows||[];if(!rows.length)throw new Error('Yahoo no ha devuelto cotizaciones para ese periodo.');const ex=await db.from('cotizaciones_historicas').select('fecha').eq('producto_id',pid).gte('fecha',start).lte('fecha',end);if(ex.error)throw ex.error;const seen=new Set((ex.data||[]).map(x=>String(x.fecha).slice(0,10)));const fresh=[...new Map(rows.filter(x=>!seen.has(x.fecha)).map(x=>[x.fecha,x])).values()];if(!fresh.length){out.textContent='No hay fechas nuevas: el histórico ya está cargado para ese periodo.';return}const payload=fresh.map(x=>({user_id:S.user.id,producto_id:pid,fecha:x.fecha,apertura:x.apertura,maximo:x.maximo,minimo:x.minimo,cierre:x.cierre,volumen:x.volumen,moneda:p.moneda||'EUR',tipo_precio:'cierre',factor_conversion:1,origen:'Yahoo Finance',fuente:'Yahoo Finance API',es_valida:true,prioridad_origen:60}));for(let i=0;i<payload.length;i+=500){const z=await db.from('cotizaciones_historicas').insert(payload.slice(i,i+500));if(z.error)throw z.error}S.qLoaded[pid]=false;out.textContent='HECHO: '+fresh.length+' cotizaciones nuevas cargadas para '+p.nombre+'.';await load()}catch(e){out.textContent='Error al recuperar Yahoo: '+(e.message||e)}}
(function(){
 const style=document.createElement('style');style.textContent='.quote-chart{margin-top:0}.chart-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.chart-head h3{margin:0 0 4px}.chart-last{text-align:right;font-size:18px;display:flex;flex-direction:column;gap:3px}.chart-ranges{display:flex;gap:7px;flex-wrap:wrap;margin:16px 0 10px}.chart-range{border:1px solid var(--l);background:#fff;color:var(--b);border-radius:9px;padding:7px 11px;font-weight:800;cursor:pointer}.chart-range.active{background:var(--b);color:#fff}.chart-wrap{width:100%;overflow:hidden;border:1px solid var(--l);border-radius:12px;background:#fff}.chart-wrap svg{display:block;width:100%;height:340px}.chart-grid{stroke:#d9e2ee;stroke-width:1}.chart-axis{fill:#71809a;font-size:12px}.chart-axis-line{stroke:#9eabc0;stroke-width:1}.chart-line{stroke:#ff4b2b;stroke-width:2.2;stroke-linejoin:round;stroke-linecap:round}.chart-range:focus{outline:2px solid #9ab8e8;outline-offset:1px}@media(max-width:600px){.chart-head{flex-direction:column}.chart-last{text-align:left}.chart-wrap svg{height:280px}.chart-range{padding:6px 9px;font-size:12px}}';document.head.appendChild(style);
 const ranges=[['7d','1 semana',7],['1m','1 mes',31],['3m','3 meses',92],['6m','6 meses',183],['1y','1 año',365],['5y','5 años',1826],['10y','10 años',3652],['all','Todo',null]];let chartRange='1y';
 const chartNum=n=>{n=Number(n)||0;const a=Math.abs(n),d=a&&a<.001?8:a<.01?6:a<.1?5:3;return new Intl.NumberFormat('es-ES',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n)};
 const chartDate=d=>d?new Intl.DateTimeFormat('es-ES').format(new Date(String(d).slice(0,10)+'T00:00:00')):'—';
 function seriesFor(p){if(account(p))return histV(p.id).slice().reverse().map(x=>({fecha:String(x.fecha).slice(0,10),valor:Number(x.valor_total)||0}));const q=histQ(p.id).slice().reverse();if(q.length)return q.map(x=>({fecha:String(x.fecha).slice(0,10),valor:Number(x.cierre)||0}));return histV(p.id).slice().reverse().map(x=>({fecha:String(x.fecha).slice(0,10),valor:Number(x.valor_total)||0}))}
 function filterSeries(a){if(!a.length||chartRange==='all')return a;const days=ranges.find(x=>x[0]===chartRange)[2],end=new Date(a[a.length-1].fecha+'T00:00:00'),start=new Date(end);start.setDate(start.getDate()-days);return a.filter(x=>new Date(x.fecha+'T00:00:00')>=start)}
 function drawChart(id){const p=S.p.find(x=>x.id===id);if(!p)return '';const all=seriesFor(p),data=filterSeries(all);if(!data.length)return '<div class="empty">No hay datos suficientes para mostrar el gráfico.</div>';const w=900,h=340,pl=62,pr=18,pt=20,pb=45,iw=w-pl-pr,ih=h-pt-pb;let min=Math.min(...data.map(x=>x.valor)),max=Math.max(...data.map(x=>x.valor));if(min===max){min*=.99;max*=1.01}const pad=(max-min)*.08||1;min-=pad;max+=pad;const x=i=>pl+(data.length===1?iw/2:iw*i/(data.length-1)),y=v=>pt+ih-(v-min)/(max-min)*ih,pts=data.map((d,i)=>x(i)+','+y(d.valor)).join(' '),ticks=5,grid=Array.from({length:ticks+1},(_,i)=>{const v=min+(max-min)*i/ticks,yy=y(v);return `<line x1="${pl}" y1="${yy}" x2="${w-pr}" y2="${yy}" class="chart-grid"/><text x="${pl-9}" y="${yy+4}" text-anchor="end" class="chart-axis">${chartNum(v)}</text>`}).join(''),first=data[0],last=data[data.length-1],change=first.valor?((last.valor/first.valor)-1)*100:0;return `<div class="quote-chart"><div class="chart-head"><div><h3>Evolución</h3><div class="sub">${account(p)?'Saldo':'Cotización / valor liquidativo'} · ${data.length} datos · ${chartDate(first.fecha)} — ${chartDate(last.fecha)}</div></div><div class="chart-last"><b>${chartNum(last.valor)} €</b><span class="${change>0?'gain':change<0?'loss':''}">${change>0?'+':''}${change.toFixed(2)} %</span></div></div><div class="chart-ranges">${ranges.map(r=>`<button class="chart-range ${chartRange===r[0]?'active':''}" onclick="window.setProductChartRange('${id}','${r[0]}')">${r[1]}</button>`).join('')}</div><div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Evolución histórica">${grid}<line x1="${pl}" y1="${pt+ih}" x2="${w-pr}" y2="${pt+ih}" class="chart-axis-line"/><polyline points="${pts}" class="chart-line" fill="none"/><text x="${pl}" y="${h-12}" class="chart-axis">${chartDate(first.fecha)}</text><text x="${w-pr}" y="${h-12}" text-anchor="end" class="chart-axis">${chartDate(last.fecha)}</text></svg></div></div>`}
 window.setProductChartRange=function(id,range){chartRange=range;const box=document.getElementById('productChart');if(box)box.innerHTML=drawChart(id)};
 const originalProduct=window.product;window.product=async function(id){await originalProduct(id);const box=document.getElementById('productChart');if(box){box.innerHTML=drawChart(id);return}const card=document.createElement('div');card.id='productChart';card.className='card';card.innerHTML=drawChart(id);const mb=document.getElementById('modalBox');if(mb){const first=mb.querySelector('.card');if(first)first.insertAdjacentElement('afterend',card);else mb.appendChild(card)}};
 const oldClose=window.closeM;window.closeM=function(){chartRange='1y';return oldClose()};
})();

(function(){
 const originalQuoteHistory=window.quoteHistory;
 const contributionType=t=>t==='Aportacion'||t==='Aportación';
 const qtyAt=(id,fecha)=>S.o.filter(x=>x.producto_id===id&&String(x.fecha).slice(0,10)<=String(fecha).slice(0,10)).sort((a,b)=>String(a.fecha).localeCompare(String(b.fecha))).reduce((a,x)=>a+delta(x),0);
 window.quoteHistory=function(id){
  const qh=histQ(id),vh=histV(id),m=new Map();
  qh.forEach(q=>{const k=String(q.fecha).slice(0,10),qtyD=Number(q.cantidad)||qtyAt(id,k),r={fecha:q.fecha,cot:q.cierre,total:q.valor_total!=null?Number(q.valor_total):qtyD?Number(q.cierre||0)*qtyD:null,origen:q.origen||'Cotización'};m.set(k,r)});
  vh.forEach(v=>{const k=String(v.fecha).slice(0,10),r=m.get(k)||{fecha:v.fecha};if(v.valor_total!=null)r.total=Number(v.valor_total);if(r.cot==null&&v.precio_unitario!=null)r.cot=Number(v.precio_unitario);if(r.cot==null&&v.valor_total!=null){const qd=qtyAt(id,k);if(qd)r.cot=Number(v.valor_total)/qd}r.origen=r.origen?r.origen+' + '+(v.origen||'Valoración'):(v.origen||'Valoración');m.set(k,r)});
  const rows=[...m.values()].sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))),page=25,start=S.historyPage*page,part=rows.slice(start,start+page);
  if(!rows.length)return '<div class="empty">Sin histórico.</div>';
  const body=part.map(r=>`<tr><td>${date(r.fecha)}</td><td>${r.cot==null?'—':num(r.cot)+' €'}</td><td>${r.total==null?'—':money(r.total)}</td><td>${esc(r.origen||'')}</td></tr>`).join('');
  const prevDisabled=start===0?'disabled':'',nextDisabled=start+page>=rows.length?'disabled':'';
  return `<div id="quoteHistoryBox"><table class="history"><thead><tr><th>Fecha</th><th>Cotización/valor</th><th>Total</th><th>Origen</th></tr></thead><tbody>${body}</tbody></table><div class="toolbar" style="margin-top:12px"><span class="sub">${start+1}-${Math.min(start+page,rows.length)} de ${rows.length}</span><span><button class="btn alt" ${prevDisabled} onclick="window.historyNav('${id}',-1)">Anterior</button> <button class="btn alt" ${nextDisabled} onclick="window.historyNav('${id}',1)">Siguiente</button></span></div></div>`;
 };
 window.historyNav=function(id,step){const qh=histQ(id),vh=histV(id),dates=new Set([...qh,...vh].map(x=>String(x.fecha).slice(0,10)));const pages=Math.max(1,Math.ceil(dates.size/25));S.historyPage=Math.max(0,Math.min(pages-1,S.historyPage+step));const box=document.getElementById('quoteHistoryBox');if(box)box.outerHTML=window.quoteHistory(id)};
 const originalOpsHistory=window.opsHistory;
 window.opsHistory=function(id){const p=S.p.find(x=>x.id===id);if(!p||!String(tn(p)).toLowerCase().includes('pension'))return originalOpsHistory(id);const a=S.o.filter(x=>x.producto_id===id).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));if(!a.length)return '<div class="empty">Sin operaciones.</div>';let prior=0,count=0;const asc=a.slice().reverse();const snapshots=new Map();for(const x of asc){const t=x.tipo_operacion||'';const isA=contributionType(t);const before=prior;if(isA){prior+=Number(x.importe_neto)||0;count++}snapshots.set(x.id,{before,after:prior,count,qty:Number(x.cantidad)||0,price:Number(x.precio_unitario)||0,isA})}return `<div class="tablewrap"><table class="history pension-ops"><thead><tr><th>Fecha</th><th>Tipo</th><th>Aportaciones anteriores</th><th>Aportación actual</th><th>Total aportado</th><th>Nº aportaciones</th><th>Participaciones</th><th>Valor aportación</th></tr></thead><tbody>${a.map(x=>{const s=snapshots.get(x.id),mov=s.isA?Number(x.importe_neto)||0:0;return `<tr><td>${date(x.fecha)}</td><td>${esc(x.tipo_operacion)}</td><td>${money(s.before)}</td><td>${s.isA?money(mov):'—'}</td><td>${money(s.after)}</td><td>${s.count}</td><td>${num(s.qty)}</td><td>${s.price?num(s.price)+' €':'—'}</td></tr>`}).join('')}</tbody></table></div>`};
 const style=document.createElement('style');style.textContent='.pension-ops{min-width:1150px}.pension-ops th,.pension-ops td{font-size:12px}.pension-ops td{vertical-align:middle}';document.head.appendChild(style);
})();
